### ISSUE TITLE
Name:'/model/embed_tokens/Gather' Status Message: CUDA error cudaErrorUnsupportedPtxVersion:the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by yufang67** [microsoft/onnxruntime-genai#1195]
**Describe the bug**
I compile the main and run the infer. i got 

generator.append_tokens(input_ids)
onnxruntime_genai.onnxruntime_genai.OrtException: Non-zero status code returned while running Gather node. Name:'/model/embed_tokens/Gather' Status Message: CUDA error cudaErrorUnsupportedPtxVersion:the provided PTX was compiled with an unsupported toolchain.

**To Reproduce**

1. i compile the latest main with pytorch:24.01-py3, https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-24-01.html
2. change infer code to 
```
generator = Generator(model, generator_params)
generator.append_tokens(input_ids)
while not generator.is_done():
    #generator.compute_logits()
    generator.generate_next_token()
    new_token = generator.get_next_tokens()[0]
```
3. rerun export and infer for biomistral model

i got error at ```generator.append_tokens``` line.

**Expected behavior**
run successfully.

**OS:**
 - OS: u22
 - pytorch:24.01-py3

**Comment by ajindal1** [comment]
@yufang67 can you please share the script you are using where you made this change? It is not entirely clear how to reproduce your error.

I just ran this script from examples/python/phi3-qa.py on GPU with a couple of Phi3 models and it works fine for me.

```
input_tokens = tokenizer.encode(prompt)
generator = og.Generator(model, params)
generator.append_tokens(input_tokens)
while not generator.is_done():
  generator.generate_next_token()
  new_token = generator.get_next_tokens()[0]
  print(tokenizer_stream.decode(new_token), end='', flush=True)
```

**Comment by yufang67** [comment]
Hi @ajindal1 ,
Thanks for the verification. i use similar code as you. i guess the issue is from my wheel. 
did you use nvidia pytorch:24.01-py3 image (u22, python3.10) to compile the wheel ?

**Comment by ajindal1** [comment]
I actually used this image nvcr.io/nvidia/pytorch:24.11-py3, it contains Ubuntu 24, Python 3.12. 

When I tried working with the image you mentioned above, I ran into the libcudnn.so.9 not found issue, which I resolved using these [instructions](https://developer.nvidia.com/cudnn-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_network)

```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
dpkg -i cuda-keyring_1.1-1_all.deb
apt-get update
apt-get -y install cudnn
```

After that I was able to run the Phi3 model successfully.

I am closing the issue for now, but if you still encounter this issue please feel free to open it again with the detailed repro steps, thanks.
