### ISSUE TITLE
[GPU] Device selection issue

### ISSUE THREAD

**Issue by ringcheng56** [microsoft/onnxruntime-genai#1545]
Hello,
I'm currently working based on the commit of [f0ae822], I'm using several GPUs on my server, so I need to select the device.
I have both explored C++ and python versions:
in C++, when I do: 
`Oga::SetCurrentGpuDeviceId(3);`
then I got:

> 2025-06-11 21:13:01.366170206 [E:onnxruntime:, inference_session.cc:2117 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:129 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; SUCCTYPE = cudnnStatus_t; std::conditional_t<THRW, void, common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; SUCCTYPE = cudnnStatus_t; std::conditional_t<THRW, void, common::Status> = void] CUDNN failure 2007: CUDNN_STATUS_BAD_PARAM_STREAM_MISMATCH ; GPU=0 ; hostname=gpumixt ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=183 ; expr=cudnnSetStream(cudnn_handle_, stream); 
> 
> 
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:129 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; SUCCTYPE = cudnnStatus_t; std::conditional_t<THRW, void, common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; SUCCTYPE = cudnnStatus_t; std::conditional_t<THRW, void, common::Status> = void] CUDNN failure 2007: CUDNN_STATUS_BAD_PARAM_STREAM_MISMATCH ; GPU=0 ; hostname=gpumixt ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=183 ; expr=cudnnSetStream(cudnn_handle_, stream); 
> 

Otherwise, if I use python:
`import onnxruntime_genai_cuda as og`
`og.set_current_gpu_device_id(1)`

I get the segmentation fault directly.

My code works very well, if I don't select the GPU number. But I need to absolutely use this function.

Anyone has any idea?
Thank you

**Comment by Eugene-M** [comment]
> In version 0.7.x, the line config.set_provider_option(execution_provider, "device_id", device_id) worked as intended. But in the latest version, I'm running into the same issue you mentioned earlier.

**Comment by Eugene-M** [comment]
> Hello, I'm currently working based on the commit of [[f0ae822](https://github.com/microsoft/onnxruntime-genai/commit/f0ae822d7fb7cbfb890a52828bf1c6c7a27f6f7d)], I'm using several GPUs on my server, so I need to select the device. I have both explored C++ and python versions: in C++, when I do: `Oga::SetCurrentGpuDeviceId(3);` then I got:
> 
> > 2025-06-11 21:13:01.366170206 [E:onnxruntime:, inference_session.cc:2117 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:129 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; SUCCTYPE = cudnnStatus_t; std::conditional_t<THRW, void, common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; SUCCTYPE = cudnnStatus_t; std::conditional_t<THRW, void, common::Status> = void] CUDNN failure 2007: CUDNN_STATUS_BAD_PARAM_STREAM_MISMATCH ; GPU=0 ; hostname=gpumixt ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=183 ; expr=cudnnSetStream(cudnn_handle_, stream);
> > terminate called after throwing an instance of 'std::runtime_error'
> > what():  Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:129 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; SUCCTYPE = cudnnStatus_t; std::conditional_t<THRW, void, common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; SUCCTYPE = cudnnStatus_t; std::conditional_t<THRW, void, common::Status> = void] CUDNN failure 2007: CUDNN_STATUS_BAD_PARAM_STREAM_MISMATCH ; GPU=0 ; hostname=gpumixt ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=183 ; expr=cudnnSetStream(cudnn_handle_, stream);
> 
> Otherwise, if I use python: `import onnxruntime_genai_cuda as og` `og.set_current_gpu_device_id(1)`
> 
> I get the segmentation fault directly.
> 
> My code works very well, if I don't select the GPU number. But I need to absolutely use this function.
> 
> Anyone has any idea? Thank you

Hey. I've found a workaround. Try to set 

`
import os
device_id=1
os.environ['CUDA_VISIBLE_DEVICES'] = str(device_id)

...
config = onnx_genai.Config(model_path)
config.clear_providers()
if model_instance_kind != 'cpu':
     config.append_provider(model_instance_kind)  #You don't need anything else here
`

**Comment by conleypri** [comment]
The error is persists in C# after trying the C# equivalent workaround.

I am running in C# with GenAI version 0.10.0 and Onnxruntime version 1.23.0. 
C# workaround:
`
   Environment.SetEnvironmentVariable("CUDA_VISIBLE_DEVICES", plngGpuId.ToString());                            
   objConfig.SetProviderOption("cuda", "device_id", plngGpuId.ToString());
`

Any further specifics on C# work around or development on this issue?

**Comment by Eugene-M** [comment]
> The error is persists in C# after trying the C# equivalent workaround.
> 
> I am running in C# with GenAI version 0.10.0 and Onnxruntime version 1.23.0. C# workaround: `Environment.SetEnvironmentVariable("CUDA_VISIBLE_DEVICES", plngGpuId.ToString());`
> 
> Any further specifics on C# work around or development on this issue?

I've double checked it on Python version GenAI version 0.10.0 with Onnxruntime version 1.23.0. And it still works. 
**You need to make sure that Environment.SetEnvironmentVariable("CUDA_VISIBLE_DEVICES", plngGpuId.ToString()) set before CUDA initialization. If the variable is not set before the CUDA initialization starts, then the driver has already seen all the devices, and the later change has no effect.**

**Comment by conleypri** [comment]
Thanks for the information It is working now for me!
