### ISSUE TITLE
CUDA EP: CUBLAS misaligned address crash during prefill with Gemma4 model

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxruntime-genai#2120]
## Description

When running Gemma4 e2b-it through GenAI with CUDA EP, the first prefill step (past_seq_length=0) crashes with a CUBLAS "misaligned address" error. Decode steps (past_seq>0) work correctly when using ORT CUDA directly.

## Environment

- ORT 1.27.0 built from source (CUDA 13.0, Flash Attention enabled)
- GenAI 0.14.0-dev (latest main including PR #2103)
- NVIDIA H200 GPUs (sm_90)
- Model: Gemma4 e2b-it exported by mobius (f16, CUDA EP with GroupQueryAttention ops)
- External data format: ONNX (4096-byte aligned) and safetensors (16-byte aligned — both crash)

## Steps to reproduce

```python
import onnxruntime_genai as og

# Model exported with:
# mobius build --model google/gemma-4-e2b-it --dtype f16 --ep cuda --runtime ort-genai --external-data onnx <output>/

model = og.Model("<model_path>")  # Loads OK, device_type=CUDA
tokenizer = og.Tokenizer(model)
ids = tokenizer.encode("Hello")

params = og.GeneratorParams(model)
params.set_search_options(max_length=50)
gen = og.Generator(model, params)
gen.append_tokens(ids)  # CRASHES HERE
```

## Error output

```
CUBLAS failure 13: the function failed to launch on the GPU
  file=onnxruntime/core/providers/cuda/math/matmul.cc ; line=325
  Node: decoder/model/layers.15/mlp/up_proj/MatMul_node_1000

CUDA failure 716: misaligned address
  file=onnxruntime/core/providers/cuda/cuda_stream_handle.cc ; line=40
```

## Root cause analysis

1. **ORT CUDA works directly** — calling `ort.InferenceSession` with `past_seq>0` produces correct logits on CUDA. The MatMul kernels execute without errors.

2. **Empty KV cache triggers the issue** — ORT's `ReduceSum` on empty tensors `{1,0}` fails on CUDA (`input_dims[axis] != 0`). GenAI's prefill path (past_seq=0) hits this.

3. **GenAI-specific** — the crash is in GenAI's KV cache management during prefill, not in the ONNX model itself.

4. **CPU works correctly** — same model generates "The capital of France is Paris." at 12.5 tok/s on CPU.

5. **Also note**: `genai_config.json` provider name format uses `"CUDAExecutionProvider"` but GenAI's dispatch map in `session_options.cpp` uses `"cuda"`. `NormalizeProviderName()` does not normalize CUDA — had to manually change config to `{"cuda": {}}`.

## Weight shapes (all multiples of 8)

```
layers.15.mlp.up_proj.weight_t: [1536, 12288]  # fp16
hidden_size=1536, intermediate_size=6144 (doubled to 12288 for double_wide_mlp)
```

## Expected behavior

CUDA generation should work end-to-end for Gemma4 models.

## Workaround

Use CPU EP (works correctly) or run ORT CUDA directly for decode steps.

**Comment by justinchuby** [comment]
## Updated Root Cause Analysis

After deeper investigation, the CUDA prefill crash has **three separate ORT-level issues**, not a GenAI config problem:

### Issue 1: CUDA ReduceSum crashes on empty tensors ✅ Fixed
**PR:** microsoft/onnxruntime#28353

The GQA rewrite rule computes `seqlens_k = ReduceSum(attention_mask, axis=1) - 1`. During prefill with `past_seq=0`, intermediate tensors have shape `{1, 0}` and ReduceSum's CUDA kernel asserts `input_dims[axis] != 0`. The CPU implementation handles this correctly.

### Issue 2: GQA `total_sequence_length=0` — CUDA graph partitioning
After ReduceSum is fixed, GQA still rejects `total_sequence_length=0`. The graph computes:
```
total_seq_len = Cast(Gather(Shape(attention_mask), 1), INT32)
```
With `attention_mask = {1, 5}`, this should be 5. But the Shape/Gather/Cast nodes run on CPU while GQA runs on CUDA. The 280 memcpy nodes in the session log confirm massive CPU↔GPU transfer overhead — the intermediate scalar values may not be transferred correctly to GQA.

**Evidence:** ORT logs show `282 Memcpy nodes are added to the graph` for default EP and `280 Memcpy nodes` for the ONNX-aligned version. These memcpy nodes are the graph partitioning placing many ops on CPU.

### Issue 3: CUBLAS misaligned address with `weight_t` tensors
For the CUDA EP model (with GQA ops), `weight_t` (pre-transposed) matrices cause CUBLAS failure 13 at `layers.15/mlp/up_proj/MatMul`. The external data is 4096-byte aligned in the ONNX file, but the CUDA memory allocator doesn't guarantee the alignment cuBLAS needs when loading external data tensors.

### Correction: genai_config is NOT the problem
The ONNX graph already computes `seqlens_k` and `total_sequence_length` internally from `attention_mask` via the GQA rewrite rule — no explicit genai_config declaration needed. GenAI correctly passes `attention_mask` which is sufficient.

### Summary

| Issue | Component | Status |
|-------|-----------|--------|
| ReduceSum on {1,0} | ORT CUDA | ✅ PR #28353 |
| GQA total_seq=0 | ORT CUDA graph partitioning | ❌ Needs investigation |
| CUBLAS misaligned address | ORT CUDA memory alignment | ❌ Needs investigation |
| 280 memcpy nodes | ORT CUDA graph partitioning | Related to Issue 2 |

**Workaround:** CPU EP works correctly at 12-15 tok/s.

**Comment by justinchuby** [comment]
## Resolution

Fixed in PR #2123. The root cause was the embedding model's `inputs_embeds` output OrtValue persisting across `Session::Run` calls.

### Root Cause

`ExtraOutputs::Update()` only clears outputs after `extra_outputs_start_`, but the embedding's `inputs_embeds` output was at index 0 (before the threshold). The stale OrtValue with the prefill shape was passed as a pre-allocated fetch to ORT, which placed it in `all_values_` at the InsertedPrecisionFreeCast output index. On the decode run with a different sequence length, ORT's shape verification failed.

### Fixes Applied (PR #2123)

1. **`Embeddings::ClearOutput()`** — null out embedding output before each Run
2. **CPU EP for embedding session** — avoid CUDA device mismatch
3. **`CopyOutputToInput`** — explicit CPU→CUDA transfer
4. **CPU `input_ids`** — device override for embedding state
5. **`DisableMemPattern`** — for decoder dynamic shapes
6. **TopK error recovery** — clear CUDA error state after benchmark failure
7. **CPU scoring** — workaround for TopK crash on vocab 262K

### Results

Gemma4 e2b-it multimodal CUDA: **68 tokens at 12.1 tok/s** on H200 GPU. Output matches CPU baseline.

**Comment by justinchuby** [comment]
Too bad of a speed

**Comment by justinchuby** [comment]
Resolved. All three modalities work on CUDA: text 158 tok/s, image ~240 tok/s, audio 126 tok/s. Fixes in GenAI PR microsoft/onnxruntime-genai#2123 + mobius PRs.
