### ISSUE TITLE
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by alexmanie** [microsoft/onnxruntime-genai#694]
After installing all CUDA, cuDNN, NVIDIA drivers, etc .... cannot load an ONNX model using onnxruntime

```bash
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/alexmanegpu2/code/app.py", line 2, in <module>
    import onnxruntime_genai as og
  File "/anaconda/envs/azureml_py38/lib/python3.9/site-packages/onnxruntime_genai/__init__.py", line 18, in <module>
    from onnxruntime_genai.onnxruntime_genai import *
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
```

If I run a search for "libcudnn.so.8" I can found it, but seems something is not properly configured at runtime.

```bash
(azureml_py38) user@hostname:~/files/code$ sudo find / -name "*libcudnn.so*"
/anaconda/envs/azureml_py38_PT_TF/lib/python3.9/site-packages/nvidia/cudnn/lib/libcudnn.so.8
/anaconda/envs/azureml_py38/lib/libcudnn.so.8
/anaconda/envs/azureml_py38/lib/libcudnn.so
/anaconda/envs/azureml_py38/lib/libcudnn.so.8.0.4
/anaconda/pkgs/cudnn-8.0.4-cuda10.1_0/lib/libcudnn.so.8
/anaconda/pkgs/cudnn-8.0.4-cuda10.1_0/lib/libcudnn.so
/anaconda/pkgs/cudnn-8.0.4-cuda10.1_0/lib/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn.so.9
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.2.1
/usr/lib/x86_64-linux-gnu/libcudnn.so
```

Can you please help with that?

Related issue was closed but cannot found a solution there: [344](https://github.com/microsoft/onnxruntime-genai/issues/344)

**Comment by MadMenHitBooker** [comment]
Hello,

Which package did you install ? I was trying with cuda 12

```shell
pip install onnxruntime-genai-cuda --pre --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
```

but it did not work, i saw you issue and noticed mine pointed to __libcudnn.so.9__
I then tried 

```shell
pip install --pre onnxruntime-genai-cuda --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-genai/pypi/simple/
```
 and it worked, for reference my files are located here 

```shell
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn.so.8.9.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/opt/conda/envs/vlm/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn.so.8
```

vlm is my virtual env

Hope it helps

**Comment by baijumeswani** [comment]
It is possible that the cudnn libs are not discoverable. Could you try adding the libcudnn path to LD_LIBRARY_PATH and try again? onnxruntime-genai probably cannot find the libcudnn path since they are not where the library expects them to be.

**Comment by iwaitu** [comment]
```
wget https://developer.download.nvidia.com/compute/cudnn/9.2.1/local_installers/cudnn-local-repo-ubuntu2204-9.2.1_1.0-1_amd64.deb
sudo dpkg -i cudnn-local-repo-ubuntu2204-9.2.1_1.0-1_amd64.deb
sudo cp /var/cudnn-local-repo-ubuntu2204-9.2.1/cudnn-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cudnn
```
After this, then you will solve it.
